name: counselor_temanbicara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^19.1.0
  flutter_quill: ^11.0.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  ionicons: ^0.2.2
  omni_datetime_picker: ^2.0.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/firebase/"

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  adaptive_icon_background: "#ffffff"
